[phases]
  [phases.setup]
    commands = ["cd backend && npm install"]

  [phases.build]
    commands = []

  [phases.start]
    commands = ["cd backend && npm start"]

[environment]
  NODE_ENV = "production"
  PORT = "3001"
